### ISSUE TITLE
Project wont start at all.

### ISSUE THREAD

**Issue by MrCaira** [christopher4lis/canvas-boilerplate#24]
The project wont work at all for me, using npm start prompts following error on Windows 11.

```
Regular expression denial of service in glob-parent - https://github.com/advisories/GHSA-ww39-953v-wcq6
PS D:\Development\Web Games\canvas-boilerplate> npm start

> canvas-template@1.0.0 start
> webpack --config webpack.config.js


webpack is watching the files…

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\Development\Web Games\canvas-boilerplate\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\Development\Web Games\canvas-boilerplate\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\Development\Web Games\canvas-boilerplate\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Development\Web Games\canvas-boilerplate\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (D:\Development\Web Games\canvas-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\Development\Web Games\canvas-boilerplate\node_modules\babel-loader\lib\index.js:59:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
PS D:\Development\Web Games\canvas-boilerplate>
```

**Comment by thomasjvu** [comment]
Use Git Bash
Navigate to the boilerplate directory
Use this command: `export NODE_OPTIONS=--openssl-legacy-provider`
Then it should work

**Comment by wasiuddinmansoori1** [comment]
after applying your code its coming like that 

![image](https://github.com/christopher4lis/canvas-boilerplate/assets/121297231/00f7c3da-af72-4254-b82a-31ff0219d3a9)

**Comment by thomasjvu** [comment]
> after applying your code its coming like that
> 
> ![image](https://user-images.githubusercontent.com/121297231/246202622-00f7c3da-af72-4254-b82a-31ff0219d3a9.png)

You have to end the quote for "--openssl-legacy-provider"

**Comment by wasiuddinmansoori1** [comment]
> $env:NODE_OPTIONS = "--openssl-legacy-provider

You Are Great! Thankyou Very Much Brother
Thanks A Lot @thomasjvu

**Comment by wasiuddinmansoori1** [comment]
Can u tell me how to get rid of typing the same command again and again to run the server. Any way by which i just need to type npm start

**Comment by DivinPrince** [comment]
thanks @thomasjvu

**Comment by Z-Hp** [comment]
It's not working for me. I used npm install and then I got this error:

`25 packages are looking for funding
  run `npm fund` for details

38 vulnerabilities (8 moderate, 24 high, 6 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.`

**Comment by vfa-linhnm** [comment]
@Z-Hp just ignore and start it when i use yarn it alert
`info This module is OPTIONAL, you can safely ignore this error`

**Comment by TheKid7878** [comment]
Strange. It opens up a tab for me saying "localhost:3000", yet the tab refuses to connect. When I inspect, it says 
"non-JS module files deprecated". Does this suggest its a network problem?? Then that's weird, because I have totally normal network.

**Comment by aravind-virtualTE** [comment]
i am getting this error 
npm start
C:\Program Files\nodejs\\node.exe: --openssl-legacy-provider
 is not allowed in NODE_OPTIONS
C:\Program Files\nodejs\\node.exe: --openssl-legacy-provider
 is not allowed in NODE_OPTIONS

**Comment by aravind-virtualTE** [comment]
people should upgrade the packages
 "@babel/core": "^7.24.5",
    "@babel/preset-env": "^7.24.5",
    "babel-loader": "^9.1.3",
    "browser-sync": "^2.29.3",
    "browser-sync-webpack-plugin": "^2.3.0",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.6.0",
    "prettier": "^3.2.5",
    "webpack": "^5.91.0",
    "webpack-cli": "^5.1.4"
